version: '1'
name: dummybank

services:
  postgresql:
    image: docker.io/bitnami/postgresql:13
    hostname: postgresql
    env_file: .docker/postgresql/.env
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/bitnami/postgresql

volumes:
  postgresql_data:
    driver: local
