version: '1'
name: dummybank

services:
  postgresql:
    image: docker.io/bitnami/postgresql:13
    hostname: postgresql
    env_file: .docker/postgresql/.env
    volumes:
      - postgresql_data:/bitnami/postgresql

  api:
    build:
      context: .
      tags:
        - 'dummybank-api:1.0.0'
    hostname: api
    env_file: .docker/api/.env
    ports:
      - 8080:8080

volumes:
  postgresql_data:
    driver: local
